// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VideoClub.Api.Data;

#nullable disable

namespace VideoClub.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VideoClub.Api.Data.Entities.Articulo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("DiasRenta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(3);

                    b.Property<bool>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<long>("GeneroId")
                        .HasColumnType("bigint");

                    b.Property<long>("IdiomaId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("MontoEntregaTardia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(10,2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("RentaPorDia")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("renta_por_dia");

                    b.Property<int>("Stock")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<long>("TipoArticuloId")
                        .HasColumnType("bigint");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GeneroId");

                    b.HasIndex("IdiomaId");

                    b.HasIndex("TipoArticuloId");

                    b.ToTable("Articulos", (string)null);
                });

            modelBuilder.Entity("VideoClub.Api.Data.Entities.Cliente", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Cedula")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<decimal>("LimiteCredito")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(10,2)")
                        .HasDefaultValue(0m);

                    b.Property<string>("NoTarjetaCr")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("char(4)")
                        .HasColumnName("no_tarjeta_cr");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TipoPersona")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Cedula")
                        .IsUnique();

                    b.ToTable("Clientes", null, t =>
                        {
                            t.HasCheckConstraint("CK_Clientes_NoTarjetaCr", "no_tarjeta_cr ~ '^[0-9]{4}$'");
                        });
                });

            modelBuilder.Entity("VideoClub.Api.Data.Entities.Elenco", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Elenco", (string)null);
                });

            modelBuilder.Entity("VideoClub.Api.Data.Entities.ElencoArticulo", b =>
                {
                    b.Property<long>("ArticuloId")
                        .HasColumnType("bigint");

                    b.Property<long>("ElencoId")
                        .HasColumnType("bigint");

                    b.Property<long>("RolId")
                        .HasColumnType("bigint");

                    b.HasKey("ArticuloId", "ElencoId", "RolId");

                    b.HasIndex("ArticuloId");

                    b.HasIndex("ElencoId");

                    b.HasIndex("RolId");

                    b.ToTable("ElencoArticulo", (string)null);
                });

            modelBuilder.Entity("VideoClub.Api.Data.Entities.Empleado", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Cedula")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateOnly>("FechaIngreso")
                        .HasColumnType("date");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("PorcientoComision")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(5,2)")
                        .HasDefaultValue(0m);

                    b.Property<string>("TandaLabor")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tanda_labor");

                    b.HasKey("Id");

                    b.HasIndex("Cedula")
                        .IsUnique();

                    b.ToTable("Empleados", null, t =>
                        {
                            t.HasCheckConstraint("CK_Empleados_TandaLabor", "tanda_labor IN ('Matutina', 'Vespertina')");
                        });
                });

            modelBuilder.Entity("VideoClub.Api.Data.Entities.Genero", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.HasKey("Id");

                    b.ToTable("Generos", (string)null);
                });

            modelBuilder.Entity("VideoClub.Api.Data.Entities.Idioma", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.HasKey("Id");

                    b.ToTable("Idiomas", (string)null);
                });

            modelBuilder.Entity("VideoClub.Api.Data.Entities.RentaDevolucion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ArticuloId")
                        .HasColumnType("bigint");

                    b.Property<int>("CantidadDias")
                        .HasColumnType("integer")
                        .HasColumnName("cantidad_dias");

                    b.Property<long>("ClienteId")
                        .HasColumnType("bigint");

                    b.Property<string>("Comentario")
                        .HasColumnType("text");

                    b.Property<int>("DiasRetraso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<long>("EmpleadoId")
                        .HasColumnType("bigint");

                    b.Property<bool>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("FechaDevolucion")
                        .HasColumnType("timestamptz")
                        .HasColumnName("fecha_devolucion");

                    b.Property<DateTime>("FechaRenta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("fecha_renta")
                        .HasDefaultValueSql("now()");

                    b.Property<decimal>("MontoXdia")
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("NoRenta")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ArticuloId");

                    b.HasIndex("ClienteId");

                    b.HasIndex("EmpleadoId");

                    b.HasIndex("FechaRenta");

                    b.HasIndex("NoRenta")
                        .IsUnique();

                    b.ToTable("RentaDevolucion", (string)null);
                });

            modelBuilder.Entity("VideoClub.Api.Data.Entities.Rol", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.HasKey("Id");

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("VideoClub.Api.Data.Entities.TipoArticulo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.HasKey("Id");

                    b.ToTable("TiposArticulos", (string)null);
                });

            modelBuilder.Entity("VideoClub.Api.Data.Entities.Articulo", b =>
                {
                    b.HasOne("VideoClub.Api.Data.Entities.Genero", "Genero")
                        .WithMany("Articulos")
                        .HasForeignKey("GeneroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VideoClub.Api.Data.Entities.Idioma", "Idioma")
                        .WithMany("Articulos")
                        .HasForeignKey("IdiomaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VideoClub.Api.Data.Entities.TipoArticulo", "TipoArticulo")
                        .WithMany("Articulos")
                        .HasForeignKey("TipoArticuloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genero");

                    b.Navigation("Idioma");

                    b.Navigation("TipoArticulo");
                });

            modelBuilder.Entity("VideoClub.Api.Data.Entities.ElencoArticulo", b =>
                {
                    b.HasOne("VideoClub.Api.Data.Entities.Articulo", "Articulo")
                        .WithMany("Elencos")
                        .HasForeignKey("ArticuloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VideoClub.Api.Data.Entities.Elenco", "Elenco")
                        .WithMany("Articulos")
                        .HasForeignKey("ElencoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VideoClub.Api.Data.Entities.Rol", "Rol")
                        .WithMany("ElencosArticulos")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Articulo");

                    b.Navigation("Elenco");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("VideoClub.Api.Data.Entities.RentaDevolucion", b =>
                {
                    b.HasOne("VideoClub.Api.Data.Entities.Articulo", "Articulo")
                        .WithMany("Rentas")
                        .HasForeignKey("ArticuloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VideoClub.Api.Data.Entities.Cliente", "Cliente")
                        .WithMany("Rentas")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VideoClub.Api.Data.Entities.Empleado", "Empleado")
                        .WithMany("Rentas")
                        .HasForeignKey("EmpleadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Articulo");

                    b.Navigation("Cliente");

                    b.Navigation("Empleado");
                });

            modelBuilder.Entity("VideoClub.Api.Data.Entities.Articulo", b =>
                {
                    b.Navigation("Elencos");

                    b.Navigation("Rentas");
                });

            modelBuilder.Entity("VideoClub.Api.Data.Entities.Cliente", b =>
                {
                    b.Navigation("Rentas");
                });

            modelBuilder.Entity("VideoClub.Api.Data.Entities.Elenco", b =>
                {
                    b.Navigation("Articulos");
                });

            modelBuilder.Entity("VideoClub.Api.Data.Entities.Empleado", b =>
                {
                    b.Navigation("Rentas");
                });

            modelBuilder.Entity("VideoClub.Api.Data.Entities.Genero", b =>
                {
                    b.Navigation("Articulos");
                });

            modelBuilder.Entity("VideoClub.Api.Data.Entities.Idioma", b =>
                {
                    b.Navigation("Articulos");
                });

            modelBuilder.Entity("VideoClub.Api.Data.Entities.Rol", b =>
                {
                    b.Navigation("ElencosArticulos");
                });

            modelBuilder.Entity("VideoClub.Api.Data.Entities.TipoArticulo", b =>
                {
                    b.Navigation("Articulos");
                });
#pragma warning restore 612, 618
        }
    }
}
