<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.5" />
    <PackageReference Include="OpenApiUi" Version="1.1.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\VideoClub.Shared\VideoClub.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Features\Productos\Commands\" />
    <Folder Include="Features\Productos\Handlers\" />
    <Folder Include="Features\Productos\Validators\" />
    <Folder Include="Controllers\" />
    <Folder Include="Data\" />
    <Folder Include="Middleware\" />
  </ItemGroup>

</Project>
